name: dexcom
description: >-
  dexcom for Dart allows you to use Dexcom Share to get your Dexcom CGM data, or anybody else's, to run your application.
version: 1.0.5
homepage: https://github.com/Calebh101/dexcom
repository: https://github.com/Calebh101/dexcom/tree/main/dart

environment:
  sdk: '^3.2.0'
  
dependencies:
  http: ^1.3.0
  intl: ^0.20.2