name: dexcom
description: >-
  dexcom for Dart allows you to use Dexcom Share to get your Dexcom CGM data, or anybody else's, to run your application. Includes time, reading, and trend.
version: 0.1.2
homepage: https://calebh101.web.app/dexcom
repository: https://github.com/Calebh101/dexcom

environment:
  sdk: '^3.2.0'
  
dependencies:
  http: ^1.2.2
  uuid: ^4.5.1
  intl: ^0.20.0