name: example
description: A sample command-line application using Dexcom.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  dexcom:
    path: ../..

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
